name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54410df6272993c77591974aff4621a218b3bea02288ed62e9f2aabb22b4f0e9"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"
