name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20e1bf0cd0d30cfe537bdac6c5837a6d70e0326c7d7afe756d6b67f1fd654db6"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"
