name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b4d76a9de2bcc5475a7f975f45d6786e7f05dae597fd983fcbe331b3ae8b229"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"
