name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66666de51759abf9aaba9b8b271b0dd7f04cab9593fb28b3fa1811be7e28deaf"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"
