name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "435cbbae6ab346f344d7c463f9022c7fa295729329a82e5fa34180e92d839fd2"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"

[options]
datapack-folder = "config/paxi/datapacks"
