name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95be1ecb0712965fea1aa4c9a6dee14b57c488e2f72872875fe639a01eba796e"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"
