name = "Don't Dye Together"
author = "P1x3l101"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1e9188bf698dab4a11d4ff99c3b004606f2ebeb90c0f36cecaf7d47a5b88d38"

[versions]
forge = "47.4.0"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.3"
