
#General settings
[General]
	#Defines the maximum level of the Cultivation Enchantment that can be achieved [Default: 4]
	#Range: 1 ~ 5
	maxAffection = 4
	#Defines the maximum level of the Yielding Enchantment that can be achieved [Default: 4]
	#Range: 1 ~ 5
	maxYieldingLevel = 4
	#Defines the durability percentage that affects the Affection Enchantment [Default: 0.01 (1%)]
	#Range: 0.01 ~ 1.0
	affectionPercentage = 0.01
	#Defines if the Avoiding Enchantment should teleport the item to world spawn upon death [Default: true]
	avoidingUponDeath = true

