
#种族属性配置系统
[races]

	#矮人族属性配置
	[races.dwarves]
		#生命值倍率
		#Range: -10.0 ~ 10.0
		max_health = -0.3
		#跟随范围倍率
		#Range: -10.0 ~ 10.0
		follow_range = 0.0
		#击退抗性
		#Range: -10.0 ~ 1.0
		knockback_resistance = 0.2
		#移动速度倍率
		#Range: -10.0 ~ 10.0
		movement_speed = 0.25
		#飞行速度倍率
		#Range: -10.0 ~ 10.0
		flying_speed = 0.0
		#攻击伤害倍率
		#Range: -10.0 ~ 10.0
		attack_damage = 0.25
		#攻击击退力度
		#Range: -10.0 ~ 10.0
		attack_knockback = 0.0
		#攻击速度倍率
		#Range: -10.0 ~ 10.0
		attack_speed = -0.25
		#护甲值加成
		#Range: -10.0 ~ 50.0
		armor = 0.0
		#护甲韧性加成
		#Range: -10.0 ~ 50.0
		armor_toughness = 0.25
		#幸运值加成
		#Range: -10.0 ~ 10.0
		luck = 1.0
		#游泳速度倍率
		#Range: -10.0 ~ 10.0
		swim_speed = 0.0
		#名称标签显示距离倍率
		#Range: -10.0 ~ 10.0
		nametag_distance = 0.0
		#重力影响倍率
		#Range: -10.0 ~ 10.0
		entity_gravity = 0.0
		#步高增加值
		#Range: -10.0 ~ 10.0
		step_height = 0.0
		#方块交互距离倍率
		#Range: -10.0 ~ 10.0
		block_reach = 0.0
		#实体交互距离倍率
		#Range: -10.0 ~ 10.0
		entity_reach = 0.0
		#矮人族体型缩放 1 为正常体型
		#Range: 0.1 ~ 10.0
		scale = 0.75
		#矮人效果魔力值增加量
		#Range: 0.0 ~ 10000.0
		manaBonus = 0.0

	#龙族属性配置
	[races.dragon]
		#生命值倍率
		#Range: -10.0 ~ 10.0
		max_health = 0.25
		#跟随范围倍率
		#Range: -10.0 ~ 10.0
		follow_range = 0.0
		#击退抗性
		#Range: -10.0 ~ 1.0
		knockback_resistance = 0.0
		#移动速度倍率
		#Range: -10.0 ~ 10.0
		movement_speed = 0.0
		#飞行速度倍率
		#Range: -10.0 ~ 10.0
		flying_speed = 0.0
		#攻击伤害倍率
		#Range: -10.0 ~ 10.0
		attack_damage = 0.5
		#攻击击退力度
		#Range: -10.0 ~ 10.0
		attack_knockback = 0.0
		#攻击速度倍率
		#Range: -10.0 ~ 10.0
		attack_speed = 0.0
		#护甲值加成
		#Range: -10.0 ~ 50.0
		armor = 0.0
		#护甲韧性加成
		#Range: -10.0 ~ 50.0
		armor_toughness = 0.5
		#幸运值加成
		#Range: -10.0 ~ 10.0
		luck = 0.0
		#游泳速度倍率
		#Range: -10.0 ~ 10.0
		swim_speed = 0.0
		#名称标签显示距离倍率
		#Range: -10.0 ~ 10.0
		nametag_distance = 0.0
		#重力影响倍率
		#Range: -10.0 ~ 10.0
		entity_gravity = 0.0
		#步高增加值
		#Range: -10.0 ~ 10.0
		step_height = 0.0
		#方块交互距离倍率
		#Range: -10.0 ~ 10.0
		block_reach = 0.0
		#实体交互距离倍率
		#Range: -10.0 ~ 10.0
		entity_reach = 0.0
		#飞行速度倍率
		#Range: -1.0 ~ 2.0
		flightSpeed = 0.3
		#魔力值加成
		#Range: 0.0 ~ 10000.0
		manaBonus = 300.0
		#每秒飞行消耗魔力值
		#Range: 0.0 ~ 1000.0
		flightManaCost = 5.0
		#魔力检查间隔(tick)
		#Range: 1.0 ~ 200.0
		manaCheckInterval = 20.0
		#每秒龙息消耗魔力
		#Range: 0.0 ~ 5000.0
		breathManaCost = 5.0
		#龙息基础伤害
		#Range: 0.0 ~ 100.0
		BreathBaseDamage = 4.0
		#龙息最小伤害
		#Range: 0.0 ~ 100.0
		BreathMinDamage = 2.0
		#龙息伤害衰减率
		#Range: 0.0 ~ 1.0
		BreathDecayRate = 0.7
		#龙族体型缩放 1 为正常体型
		#Range: 0.1 ~ 10.0
		scale = 1.2

	#精灵族属性配置
	[races.elves]
		#生命值倍率
		#Range: -10.0 ~ 10.0
		max_health = 0.0
		#跟随范围倍率
		#Range: -10.0 ~ 10.0
		follow_range = 0.0
		#击退抗性
		#Range: -10.0 ~ 1.0
		knockback_resistance = 0.0
		#移动速度倍率
		#Range: -10.0 ~ 10.0
		movement_speed = 0.1
		#飞行速度倍率
		#Range: -10.0 ~ 10.0
		flying_speed = 0.0
		#攻击伤害倍率
		#Range: -10.0 ~ 10.0
		attack_damage = -0.25
		#攻击击退力度
		#Range: -10.0 ~ 10.0
		attack_knockback = 0.0
		#攻击速度倍率
		#Range: -10.0 ~ 10.0
		attack_speed = 0.3
		#护甲值加成
		#Range: -10.0 ~ 50.0
		armor = 0.0
		#护甲韧性加成
		#Range: -10.0 ~ 50.0
		armor_toughness = 0.0
		#幸运值加成
		#Range: -10.0 ~ 10.0
		luck = 0.0
		#游泳速度倍率
		#Range: -10.0 ~ 10.0
		swim_speed = 0.0
		#名称标签显示距离倍率
		#Range: -10.0 ~ 10.0
		nametag_distance = 0.0
		#重力影响倍率
		#Range: -10.0 ~ 10.0
		entity_gravity = 0.0
		#步高增加值
		#Range: -10.0 ~ 10.0
		step_height = 0.0
		#方块交互距离倍率
		#Range: -10.0 ~ 10.0
		block_reach = 0.0
		#实体交互距离倍率
		#Range: -10.0 ~ 10.0
		entity_reach = 0.0
		#森林中额外攻击速度加成
		#Range: -1.0 ~ 10.0
		forestAttackSpeed = 0.15
		#森林中额外移动速度加成
		#Range: -1.0 ~ 10.0
		forestMovementSpeed = 0.15
		#精灵效果魔力值增加量
		#Range: 0.0 ~ 10000.0
		manaBonus = 100.0
		#潜行时弓箭伤害增加倍率
		#Range: 1.0 ~ 50.0
		bowDamageBoost = 1.5
		#精灵族体型缩放 1 为正常体型
		#Range: 0.1 ~ 10.0
		scale = 1.0

	#猫族属性配置
	[races.faeles]
		#生命值倍率
		#Range: -10.0 ~ 10.0
		max_health = -0.25
		#跟随范围倍率
		#Range: -10.0 ~ 10.0
		follow_range = 0.0
		#击退抗性
		#Range: -10.0 ~ 1.0
		knockback_resistance = 0.0
		#移动速度倍率
		#Range: -10.0 ~ 10.0
		movement_speed = 0.15
		#飞行速度倍率
		#Range: -10.0 ~ 10.0
		flying_speed = 0.0
		#攻击伤害倍率
		#Range: -10.0 ~ 10.0
		attack_damage = -0.25
		#攻击击退力度
		#Range: -10.0 ~ 10.0
		attack_knockback = 0.0
		#攻击速度倍率
		#Range: -10.0 ~ 10.0
		attack_speed = 0.15
		#护甲值加成
		#Range: -10.0 ~ 50.0
		armor = 0.0
		#护甲韧性加成
		#Range: -10.0 ~ 50.0
		armor_toughness = -0.15
		#幸运值加成
		#Range: -10.0 ~ 10.0
		luck = 2.0
		#游泳速度倍率
		#Range: -10.0 ~ 10.0
		swim_speed = 0.3
		#名称标签显示距离倍率
		#Range: -10.0 ~ 10.0
		nametag_distance = 0.0
		#重力影响倍率
		#Range: -10.0 ~ 10.0
		entity_gravity = 0.0
		#步高增加值
		#Range: -10.0 ~ 10.0
		step_height = 0.6
		#方块交互距离倍率
		#Range: -10.0 ~ 10.0
		block_reach = -0.1
		#实体交互距离倍率
		#Range: -10.0 ~ 10.0
		entity_reach = 0.0
		#空手伤害增加值
		#Range: -100.0 ~ 2000.0
		unarmedDamage = 6.0
		#每件非皮革护甲的速度惩罚
		#Range: -1.0 ~ 0.0
		armorSpeedPenalty = -0.04
		#魔力值增加量
		#Range: 0.0 ~ 10000.0
		manaBonus = 25.0
		#跳跃高度修改值
		#Range: -1.0 ~ 200.0
		jumpStrength = 0.6
		#猫猫效果是否允许攀爬墙壁
		fwallClimb = true
		#猫猫效果爬墙速度（原版梯子速度约为0.11）
		#Range: 0.05 ~ 0.3
		climbSpeed = 0.11
		#猫猫效果爬墙时的水平移动阻力
		#Range: 0.5 ~ 1.0
		climbHorizontalDrag = 0.7
		#猫族体型缩放 1 为正常体型
		#Range: 0.1 ~ 10.0
		scale = 0.85

	#仙女族属性配置
	[races.fairy]
		#生命值倍率
		#Range: -10.0 ~ 10.0
		max_health = -0.6
		#跟随范围倍率
		#Range: -10.0 ~ 10.0
		follow_range = 0.0
		#击退抗性
		#Range: -10.0 ~ 1.0
		knockback_resistance = 0.0
		#移动速度倍率
		#Range: -10.0 ~ 10.0
		movement_speed = -0.25
		#飞行速度倍率
		#Range: -10.0 ~ 10.0
		flying_speed = 0.0
		#攻击伤害倍率
		#Range: -10.0 ~ 10.0
		attack_damage = -0.75
		#攻击击退力度
		#Range: -10.0 ~ 10.0
		attack_knockback = 0.0
		#攻击速度倍率
		#Range: -10.0 ~ 10.0
		attack_speed = 0.0
		#护甲值加成
		#Range: -10.0 ~ 50.0
		armor = -0.5
		#护甲韧性加成
		#Range: -10.0 ~ 50.0
		armor_toughness = -0.25
		#幸运值加成
		#Range: -10.0 ~ 10.0
		luck = 0.0
		#游泳速度倍率
		#Range: -10.0 ~ 10.0
		swim_speed = -0.25
		#名称标签显示距离倍率
		#Range: -10.0 ~ 10.0
		nametag_distance = 0.0
		#重力影响倍率
		#Range: -10.0 ~ 10.0
		entity_gravity = 0.0
		#步高增加值
		#Range: -10.0 ~ 10.0
		step_height = -0.35
		#方块交互距离倍率
		#Range: -10.0 ~ 10.0
		block_reach = -0.35
		#实体交互距离倍率
		#Range: -10.0 ~ 10.0
		entity_reach = 0.0
		#飞行速度倍率
		#Range: -1.0 ~ 2.0
		flightSpeed = 0.3
		#魔力值增加量
		#Range: 0.0 ~ 20000.0
		manaBonus = 400.0
		#跳跃重力修改值
		#Range: -1.0 ~ 200.0
		jumpStrength = -0.25
		#仙女效果是否允许攀爬墙壁
		wallClimb = true
		#仙女效果爬墙速度（原版梯子速度约为0.11）
		#Range: 0.05 ~ 0.3
		climbSpeed = 0.11
		#仙女效果爬墙时的水平移动阻力
		#Range: 0.5 ~ 1.0
		climbHorizontalDrag = 0.7
		#仙女族体型缩放 1 为正常体型
		#Range: 0.1 ~ 10.0
		scale = 0.25

	#哥布林族属性配置
	[races.goblins]
		#生命值倍率
		#Range: -10.0 ~ 10.0
		max_health = -0.4
		#跟随范围倍率
		#Range: -10.0 ~ 10.0
		follow_range = 0.0
		#击退抗性
		#Range: -10.0 ~ 1.0
		knockback_resistance = 0.0
		#移动速度倍率
		#Range: -10.0 ~ 10.0
		movement_speed = 0.2
		#飞行速度倍率
		#Range: -10.0 ~ 10.0
		flying_speed = 0.0
		#攻击伤害倍率
		#Range: -10.0 ~ 10.0
		attack_damage = -0.5
		#攻击击退力度
		#Range: -10.0 ~ 10.0
		attack_knockback = 0.0
		#攻击速度倍率
		#Range: -10.0 ~ 10.0
		attack_speed = 0.0
		#护甲值加成
		#Range: -10.0 ~ 50.0
		armor = 0.0
		#护甲韧性加成
		#Range: -10.0 ~ 50.0
		armor_toughness = 0.0
		#幸运值加成
		#Range: -10.0 ~ 10.0
		luck = 1.0
		#游泳速度倍率
		#Range: -10.0 ~ 10.0
		swim_speed = 0.1
		#名称标签显示距离倍率
		#Range: -10.0 ~ 10.0
		nametag_distance = 0.0
		#重力影响倍率
		#Range: -10.0 ~ 10.0
		entity_gravity = 0.0
		#步高增加值
		#Range: -10.0 ~ 10.0
		step_height = 0.0
		#方块交互距离倍率
		#Range: -10.0 ~ 10.0
		block_reach = 0.0
		#实体交互距离倍率
		#Range: -10.0 ~ 10.0
		entity_reach = 0.0
		#魔力值修改量
		#Range: -10000.0 ~ 10000.0
		manaPenalty = -25.0
		#火焰和爆炸伤害减免比例
		#Range: 0.0 ~ 1.0
		damageReduction = 0.75
		#哥布林族体型缩放 1 为正常体型
		#Range: 0.1 ~ 10.0
		scale = 0.5

	#泰坦族属性配置
	[races.titan]
		#生命值倍率
		#Range: -10.0 ~ 10.0
		max_health = 1.0
		#跟随范围倍率
		#Range: -10.0 ~ 10.0
		follow_range = 0.0
		#击退抗性
		#Range: -10.0 ~ 1.0
		knockback_resistance = 1.0
		#移动速度倍率
		#Range: -10.0 ~ 10.0
		movement_speed = 0.0
		#飞行速度倍率
		#Range: -10.0 ~ 10.0
		flying_speed = 0.0
		#攻击伤害倍率
		#Range: -10.0 ~ 10.0
		attack_damage = 0.5
		#攻击击退力度
		#Range: -10.0 ~ 10.0
		attack_knockback = 0.0
		#攻击速度倍率
		#Range: -10.0 ~ 10.0
		attack_speed = -0.5
		#护甲值加成
		#Range: -10.0 ~ 50.0
		armor = 0.0
		#护甲韧性加成
		#Range: -10.0 ~ 50.0
		armor_toughness = 0.0
		#幸运值加成
		#Range: -10.0 ~ 10.0
		luck = 0.0
		#游泳速度倍率
		#Range: -10.0 ~ 10.0
		swim_speed = 0.0
		#名称标签显示距离倍率
		#Range: -10.0 ~ 10.0
		nametag_distance = 0.0
		#重力影响倍率
		#Range: -10.0 ~ 10.0
		entity_gravity = 0.0
		#步高增加值
		#Range: -10.0 ~ 10.0
		step_height = 1.4
		#方块交互距离倍率
		#Range: -10.0 ~ 10.0
		block_reach = 1.0
		#实体交互距离倍率
		#Range: -10.0 ~ 10.0
		entity_reach = 0.0
		#跳跃力量修改值
		#Range: -1.0 ~ 2.0
		jumpStrength = 0.75
		#魔力值修改量
		#Range: -10000.0 ~ 10000.0
		manaModifier = -50.0
		#水中下沉速度
		#Range: 0.0 ~ 1.0
		waterSinkSpeed = 0.1
		#泰坦族体型缩放 1 为正常体型
		#Range: 0.1 ~ 10.0
		scale = 3.0

